# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'PeriscommentViewDemo' do
    pod 'PeriscommentView', :podspec=>'../PeriscommentView.podspec'
end

target 'PeriscommentViewDemoTests' do

end
